export const SESSION_STORAGE_KEY_REFRESH_TOKEN = "FIN_THE_PEN_REFRESH_TOKEN";
export const LOCAL_STORAGE_KEY_USERS = "FIN_THE_PEN_USERS";
export const LOCAL_STORAGE_KEY_ONBOARDING = "FIN_THE_PEN_ONBOARDING";
export const LOCAL_STORAGE_KEY_SCHEDULES = "FIN_THE_PEN_SCHEDULES";
export const LOCAL_STORAGE_KEY_TEMPLATE = "FIN_THE_PEN_TEMPLATE";
export const LOCAL_STORAGE_KEY_SAVING_GOAL = "FIN_THE_PEN_SAVING_GOAL";
export const LOCAL_STORAGE_KEY_SPENDING_GOAL = "FIN_THE_PEN_SPENDING_GOAL";
export const LOCAL_STORAGE_KEY_ASSETS_BY_CATEGORY =
  "FIN_THE_PEN_ASSETS_BY_CATEGORY";
export const LOCAL_STORAGE_KEY_GOAL = "FIN_THE_PEN_GOAL";
export const COOKIE_KEY_REFRESH_TOKEN = "refresh_token";
export const COOKIE_KEY_ACCESS_TOKEN = "access_token";
