export const CATEGORY_ICONS: { [key: string]: string } = {
  급여: "salary",
  용돈: "pin-money",
  대출금: "loan",
  금융수입: "financial-income",
  사업수입: "corporate-income",
  기타: "other-income",
  식비: "food",
  카페: "cafe",
  술: "alcohol",
  "주거/통신": "residential",
  "의료/건강": "medical-health",
  "자녀/육아": "parenting",
  반려동물: "pet",
  교통수단: "transportation",
  자동차: "automobile",
  온라인결제: "online",
  "뷰티/미용": "beauty",
  "패션/쇼핑": "fashion",
  "영화/전시": "movie",
  "여행/숙박": "travel",
  "경조/선물": "events",
  구독비: "subscribe",
  대출상환: "loan-repayment",
  대출이자: "loan-interest",
};
