name: "Chromatic Deployment"

on:
  # 원하는 브랜치 명으로 바꿔주시면 됩니다.
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clean Caches and Reinstall Dependencies
        run: |
          yarn cache clean --all
          npm install -g npm@latest
          npm install -g yarn@latest
          rm -rf node_modules/ yarn.lock package-lock.json

      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
